Fix/navbar issues
pzhukovskiy/Movies-Website pull request #3
Opened 2023-04-28 14:00 UTC by pzhukovskiy

2023-05-02 12:34 UTC, od-uladzislau-lekh commented on src/components/TV/TVseries.tsx
>  const TV_SERIES = () => {
Используй PascalCase для компонентов

2023-05-11 09:29 UTC, vladlekh requested changes

2023-05-11 09:29 UTC, vladlekh commented on src/components/InfoMovie/InfoMovie.tsx
> +  async function fetchData() {
Вынеси из компонента
лучше всего создать дерикторию api и хранить там все запросы к API

2023-05-11 09:29 UTC, vladlekh commented on src/components/Login/Login.tsx
> +    const emailElement = document.getElementById('email');
Для uncontrolled компонентов надо использовать рефы

2023-05-11 09:29 UTC, vladlekh commented on src/components/Login/Login.tsx
> +            console.log("Bad user");
Давай добавим UI отображение ошибки

2023-05-11 09:29 UTC, vladlekh commented on src/components/Navbar/Navbar.tsx
> +
Дублирование кода - не очень гуд
давай сделаем hook useAuthenticatedUser

2023-05-11 09:29 UTC, vladlekh commented on src/components/Navbar/NavbarMovie.tsx
> +                    <h3 style={{paddingTop: 35, color: '#E8E8E8CC', margin: 20}}>Play movie quizes and earn free tickets</h3>
Почему не через css модули?

2023-05-11 09:29 UTC, vladlekh commented on src/components/Registration/Registration.tsx
> +      userId += 1;
Не совсем понимаю что тут происходит
ЧТо за updates объект?
Для id поля используй uuid

2023-05-11 09:29 UTC, vladlekh commented on src/components/TV/TV_SERIES.tsx
> +const TV_SERIES = () => {
Используй PascalCase для названия компонентов

2023-06-06 11:24 UTC, vladlekh approved these changes

2023-06-06 11:26 UTC, merged